# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fInventory.proto\x12\tInventory\"u\n\rInventoryItem\x12\x18\n\x10inventory_number\x18\x01 \x01(\x05\x12\x1f\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x0f.Inventory.BookH\x00\x12!\n\x06status\x18\x03 \x01(\x0e\x32\x11.Inventory.StatusB\x06\n\x04item\"Z\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05Title\x18\x02 \x01(\t\x12\x0e\n\x06\x41uthor\x18\x03 \x01(\t\x12\r\n\x05Genre\x18\x04 \x01(\t\x12\x16\n\x0ePublishingYear\x18\x05 \x01(\x05\"y\n\x11\x42ookCreateRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05Title\x18\x02 \x01(\t\x12\x0e\n\x06\x41uthor\x18\x03 \x01(\t\x12\x1f\n\x05Genre\x18\x04 \x01(\x0e\x32\x10.Inventory.Genre\x12\x16\n\x0ePublishingYear\x18\x05 \x01(\x05\"#\n\x13\x42ookRetrieveRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"j\n\x14StandardBookResponse\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05Title\x18\x02 \x01(\t\x12\x0e\n\x06\x41uthor\x18\x03 \x01(\t\x12\r\n\x05Genre\x18\x04 \x01(\t\x12\x16\n\x0ePublishingYear\x18\x05 \x01(\x05\"1\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t*=\n\x05Genre\x12\x0b\n\x07MYSTERY\x10\x00\x12\x0b\n\x07\x46ICTION\x10\x01\x12\x0f\n\x0bNON_FICTION\x10\x02\x12\t\n\x05SCIFI\x10\x03*\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x32\xa2\x01\n\tInventory\x12G\n\nCreateBook\x12\x1c.Inventory.BookCreateRequest\x1a\x19.Inventory.StatusResponse\"\x00\x12L\n\x07GetBook\x12\x1e.Inventory.BookRetrieveRequest\x1a\x1f.Inventory.StandardBookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=560
  _GENRE._serialized_end=621
  _STATUS._serialized_start=623
  _STATUS._serialized_end=657
  _INVENTORYITEM._serialized_start=30
  _INVENTORYITEM._serialized_end=147
  _BOOK._serialized_start=149
  _BOOK._serialized_end=239
  _BOOKCREATEREQUEST._serialized_start=241
  _BOOKCREATEREQUEST._serialized_end=362
  _BOOKRETRIEVEREQUEST._serialized_start=364
  _BOOKRETRIEVEREQUEST._serialized_end=399
  _STANDARDBOOKRESPONSE._serialized_start=401
  _STANDARDBOOKRESPONSE._serialized_end=507
  _STATUSRESPONSE._serialized_start=509
  _STATUSRESPONSE._serialized_end=558
  _INVENTORY._serialized_start=660
  _INVENTORY._serialized_end=822
# @@protoc_insertion_point(module_scope)
