# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fInventory.proto\x12\tInventory\"g\n\x11\x42ookCreateRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05Title\x18\x02 \x01(\t\x12\x0e\n\x06\x41uthor\x18\x03 \x01(\t\x12\r\n\x05Genre\x18\x04 \x01(\t\x12\x16\n\x0ePublishingYear\x18\x05 \x01(\x05\"#\n\x13\x42ookRetrieveRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"j\n\x14StandardBookResponse\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05Title\x18\x02 \x01(\t\x12\x0e\n\x06\x41uthor\x18\x03 \x01(\t\x12\r\n\x05Genre\x18\x04 \x01(\t\x12\x16\n\x0ePublishingYear\x18\x05 \x01(\x05\x32\xa8\x01\n\tInventory\x12M\n\nCreateBook\x12\x1c.Inventory.BookCreateRequest\x1a\x1f.Inventory.StandardBookResponse\"\x00\x12L\n\x07GetBook\x12\x1e.Inventory.BookRetrieveRequest\x1a\x1f.Inventory.StandardBookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKCREATEREQUEST._serialized_start=30
  _BOOKCREATEREQUEST._serialized_end=133
  _BOOKRETRIEVEREQUEST._serialized_start=135
  _BOOKRETRIEVEREQUEST._serialized_end=170
  _STANDARDBOOKRESPONSE._serialized_start=172
  _STANDARDBOOKRESPONSE._serialized_end=278
  _INVENTORY._serialized_start=281
  _INVENTORY._serialized_end=449
# @@protoc_insertion_point(module_scope)
